src/Entity/Data.php
<?php

namespace App\Entity;

use App\Repository\DataRepository;
use App\Service\IpcService;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DataRepository::class)
 */
class Data
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     */
    private $period;

    /**
     * @ORM\Column(type="float")
     */
    private $val;

    /**
     * @ORM\ManyToOne(targetEntity=Information::class, inversedBy="data", cascade={"remove"})
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $info;

    /**
     * @ORM\Column(type="integer")
     */
    private $days_period;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPeriod(): ?string
    {
        return $this->period;
    }

    public function setPeriod(string $period): self
    {
        $this->period = $period;

        return $this;
    }

    public function getVal(): ?float
    {
        return $this->val;
    }

    public function setVal(float $val): self
    {
        $this->val = $val;

        return $this;
    }

    public function getInfo(): ?Information
    {
        return $this->info;
    }

    public function setInfo(?Information $info): self
    {
        $this->info = $info;

        return $this;
    }

    public function getPeriodArray()
    {
        $period = $this->getFormattedPeriod();
        //Get textual representation of a month, three letters in spanish
        $month = IpcService::getMonthService($period->format('F'));
        return [
            'year' => $period->format('Y'),
            'month' => $month,
            'day' => $this->days_period,
        ];
    }

    //Create a function when get year, month, day from period, return in array

    public function getFormattedPeriod()
    {
        return \DateTime::createFromFormat('Y-m', $this->period);
    }

    public function getDaysPeriod(): ?int
    {
        return $this->days_period;
    }

    public function setDaysPeriod(int $days_period): self
    {
        $this->days_period = $days_period;

        return $this;
    }

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $ibc_original;

    /**
     * @ORM\Column(type="boolean", options={"default":0})
     */
    private $tope_aplicado = 0;

    public function getIbcOriginal(): ?float
    {
        return $this->ibc_original;
    }

    public function setIbcOriginal(?float $ibc_original): self
    {
        $this->ibc_original = $ibc_original;

        return $this;
    }

    public function getTopeAplicado(): ?bool
    {
        return $this->tope_aplicado;
    }

    public function setTopeAplicado(bool $tope_aplicado): self
    {
        $this->tope_aplicado = $tope_aplicado;

        return $this;
    }

}

src/Entity/Information.php
<?php

namespace App\Entity;

use App\Repository\InformationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=InformationRepository::class)
 */
class Information
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $full_name;

    /**
     * @ORM\Column(type="bigint")
     */
    private $Identification;

    /**
     * @ORM\Column(type="string", length=45)
     */
    private $fondo;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", unique=true)
     */
    private $uniq_id;

    /**
     * @ORM\Column(type="float")
     */
    private $total_weeks;

    /**
     * @ORM\OneToMany(targetEntity=Data::class, mappedBy="info")
     */
    private $data;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="information")

     */
    private $user;

    /**
     * @ORM\Column(type="date")
     */
    private $birthdate;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $resume = [];

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $conclusiones;

    /**
     * @ORM\Column(type="float")
     */
    private $total_weeks_original;

    /**
     * @ORM\OneToMany(targetEntity=PDFReport::class, mappedBy="information")
     * @ORM\OrderBy({"created_at"="DESC"})
     */
    private $PDFReports;

    /**
     * @ORM\Column(type="integer")
     */
    private $cotizacion_anio;

    /**
     * @ORM\OneToMany(targetEntity=Proyeccion::class, mappedBy="information")
     */
    private $proyecciones;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $total_days;

    /**
     * @ORM\Column(type="string", length=1, options={"default": "M"})
     * M = Masculino, F = Femenino
     */
    private $genero = 'M';

    /**
     * @ORM\OneToMany(targetEntity=ResumenSemanas::class, mappedBy="info")
     */
    private $resumenSemanas;

    public function __construct()
    {
        $this->data = new ArrayCollection();
        $this->PDFReports = new ArrayCollection();
        $this->proyecciones = new ArrayCollection();
        $this->resumenSemanas = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFullName(): ?string
    {
        return strtoupper($this->full_name);
    }

    public function setFullName(string $full_name): self
    {
        $this->full_name = $full_name;

        return $this;
    }

    public function getIdentification(): ?string
    {
        return $this->Identification;
    }

    public function setIdentification(string $Identification): self
    {
        $this->Identification = $Identification;
        $uniq = md5(dechex($Identification).bin2hex(random_bytes(3)));
        $this->setUniqId($uniq);
        return $this;
    }

    private function setUniqId(string $uniq_id): self
    {
        $this->uniq_id = $uniq_id;

        return $this;
    }

    public function getFondo(): ?string
    {
        return $this->fondo;
    }

    public function setFondo(string $fondo): self
    {
        $this->fondo = $fondo;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUniqId(): ?string
    {
        return $this->uniq_id;
    }

    public function getTotalWeeks(): ?float
    {
        return $this->total_weeks;
    }

    public function setTotalWeeks(float $total_weeks): self
    {
        $this->total_weeks = $total_weeks;

        return $this;
    }

    /**
     * @return Collection|Data[]
     */
    public function getData(): Collection
    {
        return $this->data;
    }

    public function addData(Data $data): self
    {
        if (!$this->data->contains($data)) {
            $this->data[] = $data;
            $data->setInfo($this);
        }

        return $this;
    }

    public function removeData(Data $data): self
    {
        if ($this->data->removeElement($data)) {
            // set the owning side to null (unless already changed)
            if ($data->getInfo() === $this) {
                $data->setInfo(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getEdad()
    {
        $hoy = new \DateTime();
        $nac = $this->getBirthdate();
        $edad = $hoy->diff($nac);
        return $edad->y;
    }

    public function getBirthdate(): ?\DateTimeInterface
    {
        return $this->birthdate;
    }

    public function setBirthdate(\DateTimeInterface $birthdate): self
    {
        $this->birthdate = $birthdate;

        return $this;
    }

    public function getResume(): ?array
    {
        return $this->resume;
    }

    public function setResume(?array $resume): self
    {
        $this->resume = $resume;

        return $this;
    }

    public function getConclusiones(): ?string
    {
        return $this->conclusiones;
    }

    public function setConclusiones(?string $conclusiones): self
    {
        $this->conclusiones = $conclusiones;

        return $this;
    }

    public function getTotalWeeksOriginal(): ?float
    {
        return $this->total_weeks_original;
    }

    public function setTotalWeeksOriginal(float $total_weeks_original): self
    {
        $this->total_weeks_original = $total_weeks_original;

        return $this;
    }

    /**
     * @return Collection|PDFReport[]
     */
    public function getPDFReports(): Collection
    {
        return $this->PDFReports;
    }

    public function addPDFReport(PDFReport $pDFReport): self
    {
        if (!$this->PDFReports->contains($pDFReport)) {
            $this->PDFReports[] = $pDFReport;
            $pDFReport->setInformation($this);
        }

        return $this;
    }

    public function removePDFReport(PDFReport $pDFReport): self
    {
        if ($this->PDFReports->removeElement($pDFReport)) {
            // set the owning side to null (unless already changed)
            if ($pDFReport->getInformation() === $this) {
                $pDFReport->setInformation(null);
                $pDFReport->removePDF();
            }
        }

        return $this;
    }

    public function getCotizacionAnio(): ?int
    {
        return $this->cotizacion_anio;
    }

    public function setCotizacionAnio(int $cotizacion_anio): self
    {
        $this->cotizacion_anio = $cotizacion_anio;

        return $this;
    }

    /**
     * @return Collection|Proyeccion[]
     */
    public function getProyecciones(): Collection
    {
        return $this->proyecciones;
    }

    public function addProyeccione(Proyeccion $proyeccione): self
    {
        if (!$this->proyecciones->contains($proyeccione)) {
            $this->proyecciones[] = $proyeccione;
            $proyeccione->setInformation($this);
        }

        return $this;
    }

    public function removeProyeccione(Proyeccion $proyeccione): self
    {
        if ($this->proyecciones->removeElement($proyeccione)) {
            // set the owning side to null (unless already changed)
            if ($proyeccione->getInformation() === $this) {
                $proyeccione->setInformation(null);
            }
        }

        return $this;
    }

    public function getTotalDays(): ?int
    {
        return $this->total_days;
    }

    public function setTotalDays(?int $total_days): self
    {
        $this->total_days = $total_days;

        return $this;
    }

    public function getGenero(): ?string
    {
        return $this->genero;
    }

    public function setGenero(string $genero): self
    {
        $this->genero = $genero;

        return $this;
    }

    public function isMujer(): bool
    {
        return $this->genero === 'F';
    }

    public function getGeneroTexto(): string
    {
        return $this->genero === 'F' ? 'Femenino' : 'Masculino';
    }

    /**
     * @return Collection|ResumenSemanas[]
     */
    public function getResumenSemanas(): Collection
    {
        return $this->resumenSemanas;
    }

    public function addResumenSemanas(ResumenSemanas $resumenSemanas): self
    {
        if (!$this->resumenSemanas->contains($resumenSemanas)) {
            $this->resumenSemanas[] = $resumenSemanas;
            $resumenSemanas->setInfo($this);
        }

        return $this;
    }

    public function removeResumenSemanas(ResumenSemanas $resumenSemanas): self
    {
        if ($this->resumenSemanas->removeElement($resumenSemanas)) {
            if ($resumenSemanas->getInfo() === $this) {
                $resumenSemanas->setInfo(null);
            }
        }

        return $this;
    }
}

src/Entity/PDFReport.php
<?php

namespace App\Entity;

use App\Repository\PDFReportRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PDFReportRepository::class)
 */
class PDFReport
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $full_path;

    /**
     * @ORM\ManyToOne(targetEntity=Information::class, inversedBy="PDFReports", cascade={"remove"})
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $information;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFullPath(): ?string
    {
        return $this->full_path;
    }

    public function setFullPath(string $full_path): self
    {
        $this->full_path = $full_path;

        return $this;
    }

    public function getInformation(): ?Information
    {
        return $this->information;
    }

    public function setInformation(?Information $information): self
    {
        $this->information = $information;

        return $this;
    }

    public function removePDF(){
        unlink($this->full_path);
        return $this;
    }
}

templates/main/client/head.html.twig
<h1 class="h2 mb-3 text-center"><b>{% if new_title is not defined %}ÚLTIMOS 10 AÑOS{% else %}{{ new_title }}{% endif %}</b></h1>
<h2 class="h2 mb-3 text-center"><b>LIQUIDACIÓN PENSIÓN RÉGIMEN DE PRIMA MEDIA</b></h2>
<h3 class="h3 mb-3 text-center text-uppercase"><b>{{ info.fullName }}</b></h3>
<div class="row">
    <dl class="col-lg-3">
        <dt>Fecha de Nacimiento</dt>
        <dd>{{ info.birthdate|date('d M Y') }} <small>{{ info.edad }} años</small></dd>
    </dl>
    <dl class="col-lg-2">
        <dt>Género
            <a href="#" data-bs-toggle="modal" data-bs-target="#modalGenero" class="text-primary" title="Editar género">
                <i class="align-middle" data-feather="edit-2" style="width:14px;height:14px;"></i>
            </a>
        </dt>
        <dd>{{ info.generoTexto }}
            {% if info.isMujer %}<span class="badge bg-info">C-197/2023</span>{% endif %}
        </dd>
    </dl>
    <dl class="col-lg-3">
        <dt>Fondo de Pensiones</dt>
        <dd class="text-uppercase">{{ info.fondo }}</dd>
    </dl>
    <dl class="col-lg-4">
        <dt>Fecha de Informe</dt>
        <dd class="text-uppercase">{{ info.createdAt|date('d/m/Y g:i a') }}</dd>
    </dl>
</div>

<!-- Modal para editar género -->
<div class="modal fade" id="modalGenero" tabindex="-1" aria-labelledby="modalGeneroLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <form action="{{ path('client_genero_update', {'uniqid': info.uniqId}) }}" method="post">
                <div class="modal-header bg-primary text-white">
                    <h5 class="modal-title" id="modalGeneroLabel">
                        Cambiar Género
                    </h5>
                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="alert alert-info mb-3">
                        <small>
                            <strong>Sentencia C-197 de 2023:</strong> Las mujeres tienen un requisito diferenciado de semanas cotizadas para acceder a la pensión.
                        </small>
                    </div>
                    <div class="form-group">
                        <label for="genero" class="form-label fw-bold">Seleccione el género:</label>
                        <select name="genero" id="genero" class="form-select form-select-lg">
                            <option value="M" {% if info.genero == 'M' %}selected{% endif %}>
                                Masculino (1,300 semanas)
                            </option>
                            <option value="F" {% if info.genero == 'F' %}selected{% endif %}>
                                Femenino ({{ semanas_mujeres|default('según año') }})
                            </option>
                        </select>
                    </div>
                    <div class="mt-3" id="infoSemanas">
                        <table class="table table-sm table-bordered">
                            <thead class="table-light">
                                <tr>
                                    <th>Año</th>
                                    <th>Semanas Mujeres</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr><td>2025</td><td>1,300</td></tr>
                                <tr><td>2026</td><td>1,250</td></tr>
                                <tr><td>2027</td><td>1,225</td></tr>
                                <tr><td>2028</td><td>1,200</td></tr>
                                <tr><td>2029</td><td>1,175</td></tr>
                                <tr><td>2030</td><td>1,150</td></tr>
                                <tr><td>2031</td><td>1,125</td></tr>
                                <tr><td>2032</td><td>1,100</td></tr>
                                <tr><td>2033</td><td>1,075</td></tr>
                                <tr><td>2034</td><td>1,050</td></tr>
                                <tr><td>2035</td><td>1,025</td></tr>
                                <tr><td>2036+</td><td>1,000</td></tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>

templates/main/client/historico.html.twig
{% extends 'base.html.twig' %}

{% block title %}Historico{% endblock %}
{% block id %}client{% endblock %}
{% block body %}
    {% include 'main/client/head.html.twig' with {'info':info} %}

    <div class="card col-12">
        <div class="card-body">
            <table class="table table-striped table-inverse table-responsive">
                <thead class="thead-inverse">
                <tr>
                    <th>Fecha de Creación</th>
                    <th>Nombre del Archivo</th>
                    <th>Acción</th>
                </tr>
                </thead>
                <tbody>
                {% for reports in info.pDFReports %}

                    <tr>
                        <td scope="row">{{ reports.createdAt|date('d/m/Y g:i a') }}</td>
                        <td>{{ reports.name }}</td>
                        <td><a href="{{ path('report_download',{'id':reports.id}) }}"
                               class="btn btn-dark btn-sm">Descargar</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
        <div class="modal fade" id="modelId" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <form action="{{ path('proyection_name') }}" method="post" class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">AGREGAR ESCENARIO</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <table class="table" id="row-range">
                        <tbody id="list-proyection">
                        {% include 'main/proyeccion.html.twig' with {'pos':1} %}
                        </tbody>
                        <tfoot>
                        <tr>
                            <td colspan="3">
                                <button class="btn btn-dark" type="button" value=1 id="agregar-fecha">Agregar Fecha
                                </button>
                            </td>
                        </tr>
                        </tfoot>
                    </table>
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="titulo">Titulo</label>
                            <textarea name="titulo" id="titulo" class="form-control"></textarea>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="hidden" name="client" value="{{ info.uniqId }}">

                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Generar</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
{% endblock %}
{% block stylesheets %}{% endblock %}

templates/main/client/importar-excel.html.twig
{% extends 'base.html.twig' %}

{% block title %}Importar Excel{% endblock %}
{% block id %}client{% endblock %}
{% block body %}
    {% include 'main/client/head.html.twig' with {'info':info} %}

    <div class="card">
        <form action="{{ path('client_carga', {'id': info.id}) }}" method="post"
              class="card-body row col-lg-12" enctype="multipart/form-data">
            <div class="col-sm-4">
                <div class="form-group">
                    <label for="file">Carga</label>
                    <div class="input-group mb-3">
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" name="file" id="file"
                                   placeholder="Pdf"
                                   required
                                   accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel"
                                   aria-describedby="fileHelpId">
                            <label class="custom-file-label" for="inputGroupFile02">Cargar Excel</label>
                            <small id="fileHelpId" class="form-text text-muted">Solo se admite
                                xlsx</small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <p><b>Nota: </b> <br>
                    Se reemplazará los valores cargados anteriormente</p>
            </div>
            <div class="col-sm-4">
                <p><b>Descargar plantilla: </b> <br>
                    <a href="{{ asset('files/Plantilla_Liquidacion.xlsx') }}">Plantilla_Liquidacion</a>
                </p>
            </div>
            <div class="form-group col-sm-12">
                <button type="submit" class="btn btn-primary">Enviar</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/main/client/reporte-mensual.html.twig
{% extends 'base.html.twig' %}

{% block title %}Resumen Mensual{% endblock %}
{% block id %}resume-mensual{% endblock %}
{% block body %}
    {% include 'main/client/head.html.twig' with {'info':info} %}

    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-lg-6 col-sm-12">
                    <h3>Años <sup class="text-secondary"><small>(Seleccionar año para ver detalles)</small></sup></h3>
                    <nav class="nav nav-pills flex-column" style="height: 40vh; overflow: scroll">
                        {% for y in years %}
                            <li class="nav-item">
                                <a href="#" class="nav-link th-year" type="button"
                                   data-target=".tr-{{ y }}"><small>{{ y }}</small></a>
                            </li>

                        {% endfor %}
                    </nav>
                </div>
                <div class="col">
                    <div class="card">
                        <div class="card-body">
                            <table class="table">
                                <tbody>
                                <tr class="bg-body">
                                    <th>Total Semanas Actual</th>
                                    <td class="text-end">{{ info.totalWeeks|number_format(2,',','.') }}</td>
                                </tr>
                                <tr>
                                    <th>Total Dias Calculadas</th>
                                    <td class="text-end">{{ dias|number_format(0,',','.') }}</td>
                                </tr>
                                <tr>
                                    <th>Total Semanas calculados por días</th>
                                    <td class="text-end">{{ (dias/7)|number_format(2,',','.') }}</td>
                                </tr>
                                </tbody>
                                <tfoot>
                                <td colspan="2">
                                    <div class="row">
                                        <a onclick="window.location.reload()" class="col btn btn-sm btn-info">Recalcular
                                            semanas</a>
                                        <form class="col" method="post"
                                              action="{{ path('client_weeks_update',{'uniqid':info.uniqId}) }}">
                                            <input type="hidden" name="value" value="{{ (dias/7)|round(2) }}">
                                            <input type="hidden" name="token" value="{{ csrf_token('update_weeks') }}">
                                            <button type="submit" class="btn btn-sm btn-outline-success">Aplicar semanas
                                                calculadas
                                            </button>
                                        </form>
                                    </div>

                                </td>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="col-12 table-responsive">
                    <table class="table table-bordered table-hover small">

                        <thead class="bg-dark text-white">
                        <tr>
                            <th>Año</th>
                            <th>Mes</th>
                            <th style="max-width: 50px">Dias cotizados</th>
                            <th>Valor</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for data in mensual %}
                            <tr class="tr tr-{{ data.periodArray.year }}" style="display: none">
                                <th>{{ data.periodArray.year }}</th>
                                <th>{{ data.periodArray.month }}</th>
                                <th><a href="#" class="dias-reporte-mensual" data-pk="{{ data.id }}"
                                       data-url="{{ path('client_actualizar_dias') }}" data-title="Dias"
                                       data-value="{{ data.periodArray.day }}">{{ data.periodArray.day }}</a></th>
                                <td class="text-end">
                                    <a href="#" class="valor-reporte-mensual" data-pk="{{ data.id }}"
                                       data-url="{{ path('client_actualizar_salario') }}" data-title="Valor"
                                       data-value="{{ data.val }}">{{ data.val }}</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
    <!-- Button trigger modal -->
    <!-- Modal -->
{% endblock %}