src/Entity/Information.php
<?php

namespace App\Entity;

use App\Repository\InformationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=InformationRepository::class)
 */
class Information
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $full_name;

    /**
     * @ORM\Column(type="bigint")
     */
    private $Identification;

    /**
     * @ORM\Column(type="string", length=45)
     */
    private $fondo;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", unique=true)
     */
    private $uniq_id;

    /**
     * @ORM\Column(type="float")
     */
    private $total_weeks;

    /**
     * @ORM\OneToMany(targetEntity=Data::class, mappedBy="info")
     */
    private $data;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="information")

     */
    private $user;

    /**
     * @ORM\Column(type="date")
     */
    private $birthdate;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $resume = [];

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $conclusiones;

    /**
     * @ORM\Column(type="float")
     */
    private $total_weeks_original;

    /**
     * @ORM\OneToMany(targetEntity=PDFReport::class, mappedBy="information")
     * @ORM\OrderBy({"created_at"="DESC"})
     */
    private $PDFReports;

    /**
     * @ORM\Column(type="integer")
     */
    private $cotizacion_anio;

    /**
     * @ORM\OneToMany(targetEntity=Proyeccion::class, mappedBy="information")
     */
    private $proyecciones;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $total_days;

    /**
     * @ORM\Column(type="string", length=1, options={"default": "M"})
     * M = Masculino, F = Femenino
     */
    private $genero = 'M';

    /**
     * @ORM\OneToMany(targetEntity=ResumenSemanas::class, mappedBy="info")
     */
    private $resumenSemanas;

    public function __construct()
    {
        $this->data = new ArrayCollection();
        $this->PDFReports = new ArrayCollection();
        $this->proyecciones = new ArrayCollection();
        $this->resumenSemanas = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFullName(): ?string
    {
        return strtoupper($this->full_name);
    }

    public function setFullName(string $full_name): self
    {
        $this->full_name = $full_name;

        return $this;
    }

    public function getIdentification(): ?string
    {
        return $this->Identification;
    }

    public function setIdentification(string $Identification): self
    {
        $this->Identification = $Identification;
        $uniq = md5(dechex($Identification).bin2hex(random_bytes(3)));
        $this->setUniqId($uniq);
        return $this;
    }

    private function setUniqId(string $uniq_id): self
    {
        $this->uniq_id = $uniq_id;

        return $this;
    }

    public function getFondo(): ?string
    {
        return $this->fondo;
    }

    public function setFondo(string $fondo): self
    {
        $this->fondo = $fondo;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUniqId(): ?string
    {
        return $this->uniq_id;
    }

    public function getTotalWeeks(): ?float
    {
        return $this->total_weeks;
    }

    public function setTotalWeeks(float $total_weeks): self
    {
        $this->total_weeks = $total_weeks;

        return $this;
    }

    /**
     * @return Collection|Data[]
     */
    public function getData(): Collection
    {
        return $this->data;
    }

    public function addData(Data $data): self
    {
        if (!$this->data->contains($data)) {
            $this->data[] = $data;
            $data->setInfo($this);
        }

        return $this;
    }

    public function removeData(Data $data): self
    {
        if ($this->data->removeElement($data)) {
            // set the owning side to null (unless already changed)
            if ($data->getInfo() === $this) {
                $data->setInfo(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getEdad()
    {
        $hoy = new \DateTime();
        $nac = $this->getBirthdate();
        $edad = $hoy->diff($nac);
        return $edad->y;
    }

    public function getBirthdate(): ?\DateTimeInterface
    {
        return $this->birthdate;
    }

    public function setBirthdate(\DateTimeInterface $birthdate): self
    {
        $this->birthdate = $birthdate;

        return $this;
    }

    public function getResume(): ?array
    {
        return $this->resume;
    }

    public function setResume(?array $resume): self
    {
        $this->resume = $resume;

        return $this;
    }

    public function getConclusiones(): ?string
    {
        return $this->conclusiones;
    }

    public function setConclusiones(?string $conclusiones): self
    {
        $this->conclusiones = $conclusiones;

        return $this;
    }

    public function getTotalWeeksOriginal(): ?float
    {
        return $this->total_weeks_original;
    }

    public function setTotalWeeksOriginal(float $total_weeks_original): self
    {
        $this->total_weeks_original = $total_weeks_original;

        return $this;
    }

    /**
     * @return Collection|PDFReport[]
     */
    public function getPDFReports(): Collection
    {
        return $this->PDFReports;
    }

    public function addPDFReport(PDFReport $pDFReport): self
    {
        if (!$this->PDFReports->contains($pDFReport)) {
            $this->PDFReports[] = $pDFReport;
            $pDFReport->setInformation($this);
        }

        return $this;
    }

    public function removePDFReport(PDFReport $pDFReport): self
    {
        if ($this->PDFReports->removeElement($pDFReport)) {
            // set the owning side to null (unless already changed)
            if ($pDFReport->getInformation() === $this) {
                $pDFReport->setInformation(null);
                $pDFReport->removePDF();
            }
        }

        return $this;
    }

    public function getCotizacionAnio(): ?int
    {
        return $this->cotizacion_anio;
    }

    public function setCotizacionAnio(int $cotizacion_anio): self
    {
        $this->cotizacion_anio = $cotizacion_anio;

        return $this;
    }

    /**
     * @return Collection|Proyeccion[]
     */
    public function getProyecciones(): Collection
    {
        return $this->proyecciones;
    }

    public function addProyeccione(Proyeccion $proyeccione): self
    {
        if (!$this->proyecciones->contains($proyeccione)) {
            $this->proyecciones[] = $proyeccione;
            $proyeccione->setInformation($this);
        }

        return $this;
    }

    public function removeProyeccione(Proyeccion $proyeccione): self
    {
        if ($this->proyecciones->removeElement($proyeccione)) {
            // set the owning side to null (unless already changed)
            if ($proyeccione->getInformation() === $this) {
                $proyeccione->setInformation(null);
            }
        }

        return $this;
    }

    public function getTotalDays(): ?int
    {
        return $this->total_days;
    }

    public function setTotalDays(?int $total_days): self
    {
        $this->total_days = $total_days;

        return $this;
    }

    public function getGenero(): ?string
    {
        return $this->genero;
    }

    public function setGenero(string $genero): self
    {
        $this->genero = $genero;

        return $this;
    }

    public function isMujer(): bool
    {
        return $this->genero === 'F';
    }

    public function getGeneroTexto(): string
    {
        return $this->genero === 'F' ? 'Femenino' : 'Masculino';
    }

    /**
     * @return Collection|ResumenSemanas[]
     */
    public function getResumenSemanas(): Collection
    {
        return $this->resumenSemanas;
    }

    public function addResumenSemanas(ResumenSemanas $resumenSemanas): self
    {
        if (!$this->resumenSemanas->contains($resumenSemanas)) {
            $this->resumenSemanas[] = $resumenSemanas;
            $resumenSemanas->setInfo($this);
        }

        return $this;
    }

    public function removeResumenSemanas(ResumenSemanas $resumenSemanas): self
    {
        if ($this->resumenSemanas->removeElement($resumenSemanas)) {
            if ($resumenSemanas->getInfo() === $this) {
                $resumenSemanas->setInfo(null);
            }
        }

        return $this;
    }
}

src/Entity/PDFReport.php
<?php

namespace App\Entity;

use App\Repository\PDFReportRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PDFReportRepository::class)
 */
class PDFReport
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $full_path;

    /**
     * @ORM\ManyToOne(targetEntity=Information::class, inversedBy="PDFReports", cascade={"remove"})
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $information;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFullPath(): ?string
    {
        return $this->full_path;
    }

    public function setFullPath(string $full_path): self
    {
        $this->full_path = $full_path;

        return $this;
    }

    public function getInformation(): ?Information
    {
        return $this->information;
    }

    public function setInformation(?Information $information): self
    {
        $this->information = $information;

        return $this;
    }

    public function removePDF(){
        unlink($this->full_path);
        return $this;
    }
}

templates/main/informes-aneriores.html.twig
{% extends 'base.html.twig' %}

{% block title %}Informes Anteriores{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css">
{% endblock %}
{% block id %}user{% endblock %}
{% block body %}

    <h1 class="h3 mb-3">Informes Anteriores</h1>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body table-responsive">
                    <table class="table table-hover table-striped" id="table-informes">
                        <thead class="thead-inverse">
                        <tr>
                            <th>Documento</th>
                            <th>Cliente</th>
                            <th>Edad</th>
                            <th>Fondo de Pensiones</th>
                            <th>Fecha de Creación</th>
                            <th>Acción</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for list in app.user.information %}
                            <tr>
                                <th scope="row" class="text-right">{{ list.identification|number_format(0) }}</th>
                                <td>{{ list.fullName }}</td>
                                <td>{{ list.edad }} años</td>
                                <td>{{ list.fondo|upper }}</td>
                                <td>{{ list.createdAt|date('Y-m-d H:i') }}</td>
                                <td>
                                    <div class="btn-group">
                                        <a class="btn btn-sm btn-primary"
                                           href="{{ path('client', {'uniqid': list.uniqid}) }}">Ver</a>
                                        <a class="btn btn-sm btn-danger eliminar-cliente"
                                           href="@" data-url="{{ path('information_remove',{'id':list.id}) }}">Eliminar</a>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    <script src="//cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#table-informes').DataTable({
                order: [[4, 'desc']],
                language: {
                    "decimal": "",
                    "emptyTable": "No hay información",
                    "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
                    "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
                    "infoFiltered": "(Filtrado de _MAX_ total entradas)",
                    "infoPostFix": "",
                    "thousands": ",",
                    "lengthMenu": "Mostrar _MENU_ Entradas",
                    "loadingRecords": "Cargando...",
                    "processing": "Procesando...",
                    "search": "Buscar:",
                    "zeroRecords": "Sin resultados encontrados",
                    "paginate": {
                        "first": "Primero",
                        "last": "Ultimo",
                        "next": "Siguiente",
                        "previous": "Anterior"
                    }
                }
            });
        });
    </script>
{% endblock %}

templates/main/reportPDF.html.twig
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>INFORME PENSIÓN - RÉGIMEN DE PRIMA MEDIA</title>
    <link rel="shortcut icon" href="https://app.liquigator.digital/img/LIQUIGATOR_.png"
          type="image/x-icon">

    <style type="text/css">
        @import url(//fonts.googleapis.com/css?family=Cambria);

        @page {
            margin: 0cm 0cm;
        }

        /** Define now the real margins of every page in the PDF **/
        body {
            margin-top: 5cm;
            margin-left: 2.54cm;
            margin-right: 2.54cm;
            margin-bottom: 2.54cm;
        }

        * {
            font-family: Cambria, Georgia, serif;
        }

        table {
            font-size: small;
        }

        tfoot tr td {
            font-weight: bold;
            font-size: small;
        }

        .gray {
            background-color: lightgray
        }

        /** Define the header rules **/
        header {
            position: fixed;
            top: 0cm;
            left: 0cm;
            right: 0cm;
            /*height: 0cm;*/
        }

        header p {
            left: 2.54cm !important;
            margin-left: 2.54cm !important;
            text-align: left;
            color: #053665;
            font-size: 20px !important;
            letter-spacing: 1px;
            font-weight: bold;
        }

        footer {
            position: fixed;
            bottom: 1cm;
            left: 0cm;
            right: 0cm;
            height: 0cm;
        }

        .page_break {
            page-break-before: always;
        }

        .page_initial {
            text-align: center;
            color: #053665;
            font-size: 150%;
        }

        .page_info {
            position: relative;
            font-size: x-large;
        }

        .page_info ul {
            position: static;
            top: 40%;
            left: 0cm;
            /*height: 30%;*/
            width: 100%;
            margin: 0% 0 0 0%;
            list-style: none;
        }

        .page_text, .page_text-ol {
            position: relative;
            font-size: large;
        }

        .page_text p {
            position: absolute;
            text-align: justify;
            top: 30%;
            left: 0cm;
            /*height: 30%;*/
            width: 100%;
            margin: -15% 0 0 0%;
        }

        .page_text-ol p {
            position: absolute;
            text-align: justify;
            top: 30%;
            left: 0cm;
            /*height: 30%;*/
            width: 100%;
            margin: -15% 0 0 0%;
        }

        .page_text-ol ol, .page_text-ol ul {
            position: absolute;
            text-align: justify;
            top: 50%;
            left: 0cm;
            /*height: 30%;*/
            width: 100%;
            margin: -15% 0 0 0%;
        }


    </style>

</head>
<body>
<header>
    <img src="{{ header }}" alt="" width="100%">
</header>
<footer>
    <img src="{{ footer }}" alt="ghfghfhgf" width="100%">
</footer>
<main>
    <div class="page_initial">
        <h1>ESTUDIO DE SU PENSIÓN</h1>
        <img src="{{ imagen_initial }}" alt="">
    </div>

    <div class="page_break"></div>

    <div class="page_info">
        <ul>
            <li><b>NOMBRE:</b> {{ info.fullName }}</li>
            <li><b>CÉDULA:</b> {{ info.identification|number_format(0,',','.') }}</li>
            <li><b>FECHA DE NACIMIENTO:</b> {{ info.birthdate|date('d/m/Y') }}</li>
            <li><b>EDAD:</b> {{ info.edad }} AÑOS</li>
            <li><b>AFILIADO(A) ACTUALMENTE EN:</b> {{ info.fondo|upper }}</li>
            <li><b>SEMANAS COTIZADAS A {{ last_record|date('M/Y')|upper }}
                    :</b> {{ info.totalWeeks|number_format(0,',','.') }}</li>
        </ul>
        <p>Este estudio profesional de su expectativa pensional le permitirá adoptar las medidas necesarias para obtener
            una pensión de acuerdo a sus necesidades.</p>
        <p>Precisiones sobre Régimen de Prima Media. </p>
        <ol>
            <li>La edad de pensión del hombre es 62 años y la mujer es 57 años</li>
            <li>Las semanas requeridas son: 1.300</li>
            <li>El ingreso Base de Liquidación se obtiene de los últimos 10 años cotizados.</li>
        </ol>
    </div>
    <div class="page_break"></div>
    <div class="page_info">
        <p>Con esta información usted podrá: <br>
            <small>&#8226; Conocer el número de semanas cotizadas</small><br>
            <small>&#8226; Saber el valor real de la pensión en el régimen de prima media</small><br>
            <small>&#8226; Le brindamos la asesoría necesaria para aumentar el monto de su pensión..</small>
        </p>
        <h4 style="text-align: center">CÓMO SE EFECTÚA LA LIQUIDACIÓN</h4>
        <p>Para la obtención de la Liquidación de la pensión en el Régimen de Prima Media (RPM) se siguen los parámetros
            que indica la Ley 100 de 1993 (Modificada por la Ley 797 de 2003) en sus artículos 21, 33 y 36: </p>
        <ol>
            <li>Se obtiene el promedio salarial de los últimos 10 años, a lo que se le
                denomina IBL (Ingreso Base de Liquidación)
            </li>
            <li>Se actualizan los salarios al año de liquidación de acuerdo al IPC
                acumulado.
            </li>
            <li>Al IBL se le aplica la tasa de reemplazo conforme a la fórmula r=
                65,5%- (s*0,5%) donde “s” es igual al número de salarios mínimos
                que representa el IBL.
            </li>
            <li>El porcentaje se incrementará en 1,5% del IBL por cada 50 semanas
                adicionales.
            </li>
        </ol>
    </div>
    <div class="page_break"></div>
    <h4 style="text-align: center">REPORTE DETALLADO</h4>
    {{ reporte|raw }}
    <h4>Conclusiones</h4>
    <div style="text-align: justify">{{ info.conclusiones|raw }}</div>
    <table width="100%">
        <tr>
            <td><h4>DETALLE</h4></td>
        </tr>
        <tr style="font-size: x-small">
            <td width="50%" valign="top">

                <table width="100%" border="0.5" cellspacing="0" cellpadding="5">
                    <tr>
                        <th>IBL</th>
                        <td style="text-align: right">{{ info.resume['IBL']|raw }}</td>
                    </tr>
                    <tr>
                        <td style="text-align: center">{{ info.resume['R'] }}</td>
                        <td style="text-align: right">{{ info.resume['R1']|raw }}</td>
                    </tr>
                    <tr>
                        <td colspan="2">&nbsp;</td>
                    </tr>
                    <tr>
                        <th style="text-align: center">{{ info.resume['X'] }}</th>
                        <th style="text-align: right">{{ info.resume['R2']|raw }}</th>
                    </tr>
                </table>
            </td>
            <td width="50%" valign="top">
                <table width="100%" border="0.5" cellspacing="0" cellpadding="5">
                    <tr>
                        <th style="text-align: center">S</th>
                        <td style="text-align: right">{{ info.resume['S'] }}</td>
                    </tr>
                    <tr>
                        <th>S.M.M.L.V</th>
                        <td style="text-align: right">{{ smmlv|number_format(0) }}</td>
                    </tr>
                </table>
                <br>
                <table width="100%" border="0.1" cellspacing="0" cellpadding="5">
                    <tr>
                        <th>% BÁSICO</th>
                        <th>% ADICIONAL</th>

                    </tr>
                    <tr>
                        <td>r=65,5%-(s*0,5%)</td>
                        <td>{{ info.totalWeeks|round(2) }} <small>Semanas</small></td>
                    </tr>
                    <tr>
                        <td>65,50%</td>
                        <td>1300 <small>Básicas</small></td>
                    </tr>
                    <tr>
                        <td>{{ info.resume['Porcentaje Adicional'] }}</td>
                        <td>{{ info.resume['Semanas Adicionales'] }} <small>Adicionales</small>
                        </td>

                    </tr>
                    <tr>
                        <td>{{ info.resume['IBL']|raw }}</td>
                        <td>1.5%</td>
                    </tr>
                    <tr style="background-color: lightgray">
                        <th>SUMA</th>
                        <td>{{ info.resume['X'] }}</td>
                    </tr>
                </table>

            </td>
        </tr>
    </table>
    <div class="page_break"></div>
<div style="font-size: large;text-align: justify">
    <table style="width: 100%;">
        <tr>
            <th width="50%" style="text-align: center"><h3 style="font-size: large">INFORME ELABORADO POR <BR> <B>FABIÁN GUARÍN</B></h3></th>
            <th width="50%"><img src="{{ elaborado_por }}" alt="" width="80%"></th>
        </tr>
    </table>
    <p>Abogado dedicado a ejercer en asuntos relacionados con
        Pensiones. Experiencia de más de 20 años, Catedrático en
        Pensiones en la especialización en derecho laboral, egresado de la
        Universidad Externado de Colombia, especializado en Derecho
        Laboral y Magíster en derecho del trabajo de la misma
        Universidad. Además cuenta con un Master en Administración de
        Empresas (MBA ) del INALDE – Universidad de la Sabana y
        especialización de derecho de los negocios.</p>
    <p>
        Su experiencia profesional ha sido adquirida como asesor y
        consultor Jurídico en el Banco Colpatria, en la Fiduciaria la
        Previsora S.A, Abogado Especializado de la Dirección Jurídica
        Nacional del Instituto de Seguros Sociales .
    </p>
    <p>
        La consultoría que se suministra está dirigida a independientes,
        trabajadores y pensionados con problemas relacionadas con el
        régimen aplicable y su respectiva liquidación.</p>
</div>



</main>

</body>
</html>

templates/main/reportPreliminar.html.twig
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>REPORTE PRELIMINAR PENSIÓN - RÉGIMEN DE PRIMA MEDIA</title>
    <link rel="shortcut icon" href="https://app.liquigator.digital/img/LIQUIGATOR_.png"
          type="image/x-icon">

    <style type="text/css">
        @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap');

        @page {
            margin: 0cm 0cm;
        }

        /** Define now the real margins of every page in the PDF **/
        body {
            margin-top: 2.54cm;
            margin-left: 2.54cm;
            margin-right: 2.54cm;
            margin-bottom: 2.54cm;
            font-size: small;

        }

        * {
            font-family: 'Roboto', sans-serif;
        }

        table {
            font-size: small;
        }

        tfoot tr td {
            font-weight: bold;
            font-size: small;
        }

        .gray {
            background-color: lightgray
        }

        /** Define the header rules **/
        header {
            position: fixed;
            top: 0cm;
            left: 0cm;
            right: 0cm;
            /*height: 0cm;*/
        }

        header p {
            left: 2.54cm !important;
            margin-left: 2.54cm !important;
            text-align: left;
            color: #053665;
            font-size: 12px !important;
            letter-spacing: 1px;
            font-weight: bold;
        }

        footer {
            position: fixed;
            bottom: 1cm;
            left: 0cm;
            right: 0cm;
            height: 0cm;
        }

        .page_break {
            page-break-before: always;
        }

        .page_initial {
            text-align: center;
            color: #053665;
            font-size: 150%;
        }

        .page_info {
            position: relative;
            font-size: small;
        }

        .page_info ul {
            /*position: absolute;*/
            left: 0cm;
            /*height: 30%;*/
            width: 100%;
            list-style: none;
        }

        .page_text, .page_text-ol {
            position: relative;
            font-size: x-large;
        }

        .page_text p {
            position: absolute;
            text-align: justify;
            top: 40%;
            left: 0cm;
            /*height: 30%;*/
            width: 100%;
            margin: -15% 0 0 0%;
        }

        .page_text-ol p {
            position: absolute;
            text-align: justify;
            top: 30%;
            left: 0cm;
            /*height: 30%;*/
            width: 100%;
            margin: -15% 0 0 0%;
        }

        .page_text-ol ol, .page_text-ol ul {
            position: absolute;
            text-align: justify;
            top: 50%;
            left: 0cm;
            /*height: 30%;*/
            width: 100%;
            margin: -15% 0 0 0%;
        }


    </style>

</head>
<body>

<main>

    <div class="page_info">
        <h3>INFORME PRELIMINAR</h3>
        <ul>
            <li><b>NOMBRE:</b> {{ info.fullName }}</li>
            <li><b>CÉDULA:</b> {{ info.identification|number_format(0,',','.') }}</li>
            <li><b>FECHA DE NACIMIENTO:</b> {{ info.birthdate|date('d/m/Y') }}</li>
            <li><b>EDAD:</b> {{ info.edad }} AÑOS</li>
            <li><b>AFILIADO(A) ACTUALMENTE EN:</b> {{ info.fondo|upper }}</li>
            <li><b>SEMANAS COTIZADAS A {{ last_record|date('M/Y')|upper }}
                    :</b> {{ info.totalWeeks|number_format(0,',','.') }}</li>
        </ul>

        <h4 style="text-align: center">REPORTE DETALLADO</h4>
        {{ reporte|raw }}
        <table width="100%">
            <tr>
                <td><h4>DETALLE</h4></td>
            </tr>
            <tr style="font-size: x-small">
                <td width="50%" valign="top">

                    <table width="100%" border="0.5" cellspacing="0" cellpadding="5">
                        <tr>
                            <th>IBL</th>
                            <td style="text-align: right">{{ info.resume['IBL']|raw }}</td>
                        </tr>
                        <tr>
                            <td style="text-align: center">{{ info.resume['R'] }}</td>
                            <td style="text-align: right">{{ info.resume['R1']|raw }}</td>
                        </tr>
                        <tr>
                            <td colspan="2">&nbsp;</td>
                        </tr>
                        <tr>
                            <th style="text-align: center">{{ info.resume['X'] }}</th>
                            <th style="text-align: right">{{ info.resume['R2']|raw }}</th>
                        </tr>
                    </table>
                </td>
                <td width="50%" valign="top">
                    <table width="100%" border="0.5" cellspacing="0" cellpadding="5">
                        <tr>
                            <th style="text-align: center">S</th>
                            <td style="text-align: right">{{ info.resume['S'] }}</td>
                        </tr>
                        <tr>
                            <th>S.M.M.L.V</th>
                            <td style="text-align: right">{{ smmlv|number_format(0) }}</td>
                        </tr>
                    </table>
                    <br>
                    <table width="100%" border="0.1" cellspacing="0" cellpadding="5">
                        <tr>
                            <th>% BÁSICO</th>
                            <th>% ADICIONAL</th>

                        </tr>
                        <tr>
                            <td>r=65,5%-(s*0,5%)</td>
                            <td>{{ info.totalWeeks|round(2) }} <small>Semanas</small></td>
                        </tr>
                        <tr>
                            <td>65,50%</td>
                            <td>1300 <small>Básicas</small></td>
                        </tr>
                        <tr>
                            <td>{{ info.resume['Porcentaje Adicional'] }}</td>
                            <td>{{ info.resume['Semanas Adicionales'] }} <small>Adicionales</small>
                            </td>

                        </tr>
                        <tr>
                            <td>{{ info.resume['IBL']|raw }}</td>
                            <td>1.5%</td>
                        </tr>
                        <tr style="background-color: lightgray">
                            <th>SUMA</th>
                            <td>{{ info.resume['X'] }}</td>
                        </tr>
                    </table>

                </td>
            </tr>
        </table>
        <h4>Conclusiones</h4>
        <div style="text-align: justify">{{ info.conclusiones|raw }}</div>

    </div>
</main>

</body>
</html>